//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(GestionReservasMetadata))]
    public partial class GestionReservas
    {
        public int IDReserva { get; set; }
        public int IDUsuario { get; set; }
        public int IDEspacio { get; set; }
        public System.DateTime fecha { get; set; }
        public bool estado { get; set; }
    
        public virtual Espacios Espacios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
