//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(GestionAsignacionPlanesMetadata))]
    public partial class GestionAsignacionPlanes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestionAsignacionPlanes()
        {
            this.GestionResidencias = new HashSet<GestionResidencias>();
        }
    
        public int IDAsignacion { get; set; }
        public int IDPlan { get; set; }
        public System.DateTime fechaAsignacion { get; set; }
        public bool estadoPago { get; set; }
    
        public virtual GestionPlanCobros GestionPlanCobros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionResidencias> GestionResidencias { get; set; }
    }
}
