//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(GestionAsignacionPlanesMetadata))]
    public partial class GestionAsignacionPlanes
    {
        public int IDAsignacion { get; set; }
        public int IDResidencia { get; set; }
        public int IDPlan { get; set; }
        public System.DateTime fechaAsignacion { get; set; }
        public bool estadoPago { get; set; }
        public System.DateTime fechaPago { get; set; }
        public int MesSeleccionado { get; set; }
        public int AnnoSeleccionado { get; set; }

        public virtual GestionPlanCobros GestionPlanCobros { get; set; }
        public virtual GestionResidencias GestionResidencias { get; set; }
    }
}
