//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(GestionReservasMetadata))]
    public partial class GestionReservas
    {
        public int IDReserva { get; set; }
        public int IDUsuario { get; set; }
        public int IDEspacio { get; set; }
        public System.DateTime fecha { get; set; }
        public bool estado { get; set; }
    
        public virtual Espacios Espacios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
