//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(GestionResidenciasMetadata))]
    public partial class GestionResidencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestionResidencias()
        {
            this.Carros = new HashSet<Carros>();
            this.GestionAsignacionPlanes = new HashSet<GestionAsignacionPlanes>();
            this.PersonasResidentes = new HashSet<PersonasResidentes>();
        }
    
        public int IDResidencia { get; set; }
        public int IDUsuario { get; set; }
        public int cantPersonas { get; set; }
        public int IDEstadoResidencia { get; set; }
        public int annoInicio { get; set; }
        public int cantCarros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carros> Carros { get; set; }
        public virtual EstadoResidencia EstadoResidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionAsignacionPlanes> GestionAsignacionPlanes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonasResidentes> PersonasResidentes { get; set; }
    }
}
