//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lumincondo_DBEntities : DbContext
    {
        public Lumincondo_DBEntities()
            : base("name=Lumincondo_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carros> Carros { get; set; }
        public virtual DbSet<Espacios> Espacios { get; set; }
        public virtual DbSet<EstadoIncidencia> EstadoIncidencia { get; set; }
        public virtual DbSet<EstadoResidencia> EstadoResidencia { get; set; }
        public virtual DbSet<GestionAsignacionPlanes> GestionAsignacionPlanes { get; set; }
        public virtual DbSet<GestionPlanCobros> GestionPlanCobros { get; set; }
        public virtual DbSet<GestionReservas> GestionReservas { get; set; }
        public virtual DbSet<GestionResidencias> GestionResidencias { get; set; }
        public virtual DbSet<GestionRubrosCobros> GestionRubrosCobros { get; set; }
        public virtual DbSet<Informacion> Informacion { get; set; }
        public virtual DbSet<PersonasResidentes> PersonasResidentes { get; set; }
        public virtual DbSet<ReporteIncidencias> ReporteIncidencias { get; set; }
        public virtual DbSet<TipoInformacion> TipoInformacion { get; set; }
        public virtual DbSet<TiposUsuarios> TiposUsuarios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
