//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasResidentes
    {
        public int IDCedula { get; set; }
        public int IDResidencia { get; set; }
        public string nombre { get; set; }
    
        public virtual GestionResidencias GestionResidencias { get; set; }
    }
}
