//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ReporteIncidenciasMetadata))]
    public partial class ReporteIncidencias
    {
        public int IDIncidencia { get; set; }
        public int IDEstado { get; set; }
        public int IDUsuario { get; set; }
        public string descripcion { get; set; }
    
        public virtual EstadoIncidencia EstadoIncidencia { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
