//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(UsuariosMetadata))]
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.GestionReservas = new HashSet<GestionReservas>();
            this.GestionResidencias = new HashSet<GestionResidencias>();
            this.ReporteIncidencias = new HashSet<ReporteIncidencias>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string contrasenna { get; set; }
        public int IDTipoUsuario { get; set; }
        public string email { get; set; }
        public bool estado { get; set; }
        public int telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionReservas> GestionReservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionResidencias> GestionResidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteIncidencias> ReporteIncidencias { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
    }
}
